// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package split

import (
	"github.com/splitio/go-client/v6/splitio/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BlockUntilReady provides a mock function for the type MockClient
func (_mock *MockClient) BlockUntilReady(timer int) error {
	ret := _mock.Called(timer)

	if len(ret) == 0 {
		panic("no return value specified for BlockUntilReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(timer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_BlockUntilReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockUntilReady'
type MockClient_BlockUntilReady_Call struct {
	*mock.Call
}

// BlockUntilReady is a helper method to define mock.On call
//   - timer int
func (_e *MockClient_Expecter) BlockUntilReady(timer interface{}) *MockClient_BlockUntilReady_Call {
	return &MockClient_BlockUntilReady_Call{Call: _e.mock.On("BlockUntilReady", timer)}
}

func (_c *MockClient_BlockUntilReady_Call) Run(run func(timer int)) *MockClient_BlockUntilReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_BlockUntilReady_Call) Return(err error) *MockClient_BlockUntilReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_BlockUntilReady_Call) RunAndReturn(run func(timer int) error) *MockClient_BlockUntilReady_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockClient
func (_mock *MockClient) Destroy() {
	_mock.Called()
	return
}

// MockClient_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockClient_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockClient_Expecter) Destroy() *MockClient_Destroy_Call {
	return &MockClient_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockClient_Destroy_Call) Run(run func()) *MockClient_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Destroy_Call) Return() *MockClient_Destroy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Destroy_Call) RunAndReturn(run func()) *MockClient_Destroy_Call {
	_c.Run(run)
	return _c
}

// Track provides a mock function for the type MockClient
func (_mock *MockClient) Track(key string, trafficType string, eventType string, value interface{}, properties map[string]interface{}) error {
	ret := _mock.Called(key, trafficType, eventType, value, properties)

	if len(ret) == 0 {
		panic("no return value specified for Track")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, interface{}, map[string]interface{}) error); ok {
		r0 = returnFunc(key, trafficType, eventType, value, properties)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MockClient_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - key string
//   - trafficType string
//   - eventType string
//   - value interface{}
//   - properties map[string]interface{}
func (_e *MockClient_Expecter) Track(key interface{}, trafficType interface{}, eventType interface{}, value interface{}, properties interface{}) *MockClient_Track_Call {
	return &MockClient_Track_Call{Call: _e.mock.On("Track", key, trafficType, eventType, value, properties)}
}

func (_c *MockClient_Track_Call) Run(run func(key string, trafficType string, eventType string, value interface{}, properties map[string]interface{})) *MockClient_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		var arg4 map[string]interface{}
		if args[4] != nil {
			arg4 = args[4].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_Track_Call) Return(err error) *MockClient_Track_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Track_Call) RunAndReturn(run func(key string, trafficType string, eventType string, value interface{}, properties map[string]interface{}) error) *MockClient_Track_Call {
	_c.Call.Return(run)
	return _c
}

// TreatmentWithConfig provides a mock function for the type MockClient
func (_mock *MockClient) TreatmentWithConfig(key interface{}, featureFlagName string, attributes map[string]interface{}) client.TreatmentResult {
	ret := _mock.Called(key, featureFlagName, attributes)

	if len(ret) == 0 {
		panic("no return value specified for TreatmentWithConfig")
	}

	var r0 client.TreatmentResult
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, map[string]interface{}) client.TreatmentResult); ok {
		r0 = returnFunc(key, featureFlagName, attributes)
	} else {
		r0 = ret.Get(0).(client.TreatmentResult)
	}
	return r0
}

// MockClient_TreatmentWithConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TreatmentWithConfig'
type MockClient_TreatmentWithConfig_Call struct {
	*mock.Call
}

// TreatmentWithConfig is a helper method to define mock.On call
//   - key interface{}
//   - featureFlagName string
//   - attributes map[string]interface{}
func (_e *MockClient_Expecter) TreatmentWithConfig(key interface{}, featureFlagName interface{}, attributes interface{}) *MockClient_TreatmentWithConfig_Call {
	return &MockClient_TreatmentWithConfig_Call{Call: _e.mock.On("TreatmentWithConfig", key, featureFlagName, attributes)}
}

func (_c *MockClient_TreatmentWithConfig_Call) Run(run func(key interface{}, featureFlagName string, attributes map[string]interface{})) *MockClient_TreatmentWithConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_TreatmentWithConfig_Call) Return(treatmentResult client.TreatmentResult) *MockClient_TreatmentWithConfig_Call {
	_c.Call.Return(treatmentResult)
	return _c
}

func (_c *MockClient_TreatmentWithConfig_Call) RunAndReturn(run func(key interface{}, featureFlagName string, attributes map[string]interface{}) client.TreatmentResult) *MockClient_TreatmentWithConfig_Call {
	_c.Call.Return(run)
	return _c
}

// TreatmentsWithConfigByFlagSet provides a mock function for the type MockClient
func (_mock *MockClient) TreatmentsWithConfigByFlagSet(key interface{}, flagSet string, attributes map[string]interface{}) map[string]client.TreatmentResult {
	ret := _mock.Called(key, flagSet, attributes)

	if len(ret) == 0 {
		panic("no return value specified for TreatmentsWithConfigByFlagSet")
	}

	var r0 map[string]client.TreatmentResult
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, map[string]interface{}) map[string]client.TreatmentResult); ok {
		r0 = returnFunc(key, flagSet, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]client.TreatmentResult)
		}
	}
	return r0
}

// MockClient_TreatmentsWithConfigByFlagSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TreatmentsWithConfigByFlagSet'
type MockClient_TreatmentsWithConfigByFlagSet_Call struct {
	*mock.Call
}

// TreatmentsWithConfigByFlagSet is a helper method to define mock.On call
//   - key interface{}
//   - flagSet string
//   - attributes map[string]interface{}
func (_e *MockClient_Expecter) TreatmentsWithConfigByFlagSet(key interface{}, flagSet interface{}, attributes interface{}) *MockClient_TreatmentsWithConfigByFlagSet_Call {
	return &MockClient_TreatmentsWithConfigByFlagSet_Call{Call: _e.mock.On("TreatmentsWithConfigByFlagSet", key, flagSet, attributes)}
}

func (_c *MockClient_TreatmentsWithConfigByFlagSet_Call) Run(run func(key interface{}, flagSet string, attributes map[string]interface{})) *MockClient_TreatmentsWithConfigByFlagSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]interface{}
		if args[2] != nil {
			arg2 = args[2].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_TreatmentsWithConfigByFlagSet_Call) Return(stringToTreatmentResult map[string]client.TreatmentResult) *MockClient_TreatmentsWithConfigByFlagSet_Call {
	_c.Call.Return(stringToTreatmentResult)
	return _c
}

func (_c *MockClient_TreatmentsWithConfigByFlagSet_Call) RunAndReturn(run func(key interface{}, flagSet string, attributes map[string]interface{}) map[string]client.TreatmentResult) *MockClient_TreatmentsWithConfigByFlagSet_Call {
	_c.Call.Return(run)
	return _c
}
