version: '3'

# Split OpenFeature Provider - Task Runner
# Streamlined for essential development tasks

silent: true

vars:
  COVERAGE_FILE: coverage.out

tasks:
  # ============================================================================
  # Core Development Tasks
  # ============================================================================

  default:
    desc: Run all quality checks (lint, test, coverage)
    cmds:
      - task: lint
      - task: test
      - task: coverage-check

  build:
    desc: Build the provider
    cmds:
      - go build -v ./...

  clean:
    desc: Clean build artifacts and test outputs
    cmds:
      - rm -f {{.COVERAGE_FILE}}
      - rm -rf .task/
      - go clean -cache -testcache

  # ============================================================================
  # Testing Tasks
  # ============================================================================

  test:
    desc: Run unit tests with race detector and coverage (excludes examples and integration tests)
    cmds:
      - go test -v -race -coverprofile={{.COVERAGE_FILE}} -covermode=atomic $(go list ./... | grep -v /examples/ | grep -v /test/)
      - task: update-coverage-badge

  test-short:
    desc: Run unit tests in short mode (excludes examples and integration tests)
    cmds:
      - go test -v -short $(go list ./... | grep -v /examples/ | grep -v /test/)

  # ============================================================================
  # Coverage Tasks
  # ============================================================================

  coverage:
    desc: Generate test coverage report
    deps: [ test ]
    cmds:
      - go tool cover -func={{.COVERAGE_FILE}}

  coverage-check:
    desc: Check if coverage meets 70% threshold
    deps: [ test ]
    cmds:
      - |
        COVERAGE=$(go tool cover -func={{.COVERAGE_FILE}} | grep total | awk '{print $3}' | sed 's/%//')
        THRESHOLD=70
        echo "Coverage: $COVERAGE%"
        if [ $(echo "$COVERAGE < $THRESHOLD" | bc) -eq 1 ]; then
          echo "Coverage $COVERAGE% is below threshold $THRESHOLD%"
          exit 1
        else
          echo "Coverage $COVERAGE% meets threshold $THRESHOLD%"
        fi

  update-coverage-badge:
    desc: Update README coverage badge with current coverage
    internal: true
    cmds:
      - |
        # Extract coverage from existing coverage file (generated by test task)
        COVERAGE=$(go tool cover -func={{.COVERAGE_FILE}} | grep total | awk '{print $3}' | sed 's/%//')
        echo "Updating README coverage badge to $COVERAGE%"
        sed -i.bak "s/coverage-[0-9.]*%25/coverage-$COVERAGE%25/g" README.md
        rm -f README.md.bak
        echo "Coverage badge updated to $COVERAGE%"

  # ============================================================================
  # Code Quality Tasks
  # ============================================================================

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run --timeout 5m

  lint-fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix --timeout 5m

  fmt:
    desc: Format code with gofmt
    cmds:
      - gofmt -s -w .

  fmt-check:
    desc: Check if code is formatted
    cmds:
      - |
        UNFORMATTED=$(gofmt -l .)
        if [ -n "$UNFORMATTED" ]; then
          echo "The following files are not formatted:"
          echo "$UNFORMATTED"
          exit 1
        else
          echo "All files are properly formatted"
        fi

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  # ============================================================================
  # CI/CD Tasks
  # ============================================================================

  ci:
    desc: Run all CI checks (use this before submitting PR)
    cmds:
      - echo "Running CI checks..."
      - task: fmt-check
      - task: lint
      - task: vet
      - task: test
      - task: coverage-check
      - echo "All CI checks passed!"

  pre-commit:
    desc: Run pre-commit checks (format, lint, test)
    cmds:
      - task: fmt
      - task: lint
      - task: test-short

  pre-push:
    desc: Run pre-push checks (full CI)
    cmds:
      - task: ci

  # ============================================================================
  # Example Tasks
  # ============================================================================

  example-cloud:
    desc: Run cloud example with streaming mode and colored logs (requires SPLIT_API_KEY)
    dir: examples/cloud
    cmds:
      - go run main.go

  example-localhost:
    desc: Run localhost mode example with offline YAML flags (no account needed)
    dir: examples/localhost
    cmds:
      - go run main.go

  # ============================================================================
  # Integration Testing
  # ============================================================================

  integration-test:
    desc: Run integration test suite in localhost mode (no API key needed)
    dir: test/integration
    cmds:
      - go run .

  advanced-test:
    desc: Run advanced test for cloud-only features (requires SPLIT_API_KEY)
    dir: test/advanced
    cmds:
      - go run main.go

  # ============================================================================
  # Dependency Management
  # ============================================================================

  deps-tidy:
    desc: Tidy go.mod and go.sum
    cmds:
      - go mod tidy

  deps-update:
    desc: Update all dependencies to latest versions
    cmds:
      - echo "Updating all dependencies..."
      - go get -u ./...
      - go mod tidy
      - echo "Dependencies updated!"
      - echo "Run 'task test' to verify compatibility"

  # ============================================================================
  # Tool Installation
  # ============================================================================

  install-tools:
    desc: Install all required development tools
    cmds:
      - echo "Installing development tools..."
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - echo "All tools installed!"

  check-tools:
    desc: Check if required tools are installed
    cmds:
      - |
        echo "Checking required tools..."
        MISSING=""

        if ! command -v golangci-lint &> /dev/null; then
          echo "golangci-lint not installed"
          MISSING="$MISSING golangci-lint"
        else
          echo "golangci-lint installed"
        fi

        if [ -n "$MISSING" ]; then
          echo ""
          echo "Run 'task install-tools' to install missing tools"
          exit 1
        else
          echo ""
          echo "All required tools are installed!"
        fi

  # ============================================================================
  # Help
  # ============================================================================

  help:
    desc: Show help and common workflows
    cmds:
      - |
        echo "Split OpenFeature Provider - Task Runner"
        echo "========================================"
        echo ""
        echo "Common Workflows:"
        echo ""
        echo "  Quick Start:"
        echo "    task install-tools    # Install development tools"
        echo "    task test             # Run tests (auto-updates README coverage)"
        echo ""
        echo "  Development:"
        echo "    task                  # Run default checks (lint + test + coverage)"
        echo "    task pre-commit       # Before committing"
        echo ""
        echo "  Before PR:"
        echo "    task ci               # Run all CI checks"
        echo "    task coverage-check   # Verify coverage threshold"
        echo ""
        echo "  Code Quality:"
        echo "    task lint             # Run linter"
        echo "    task fmt              # Format code"
        echo "    task vet              # Run go vet"
        echo ""
        echo "  Examples:"
        echo "    task example-localhost # Offline mode with YAML (no account)"
        echo "    task example-cloud     # Cloud mode with streaming (needs API key)"
        echo ""
        echo "  Integration Testing:"
        echo "    task integration-test  # Localhost mode (no API key needed)"
        echo "    task advanced-test     # Cloud-only features (needs API key)"
        echo ""
        echo "Run 'task --list' to see all available tasks"
